#!/bin/bash

path=$(pwd)
while [ ! "$(ls -1 $path | grep NEXT)" ]; do
path=$path"/.."
done
cd $path

project=$(pwd | sed 's/\// /g' | awk '{print $NF}')

### ### ###

if [ $HOSTNAME = amethyst ] ; then
# Sat  8 Apr 09:18:52 EDT 2023
dd=$(date | awk '{print $2}')
mm=$(date | awk '{print $3}')
yy=$(date | awk '{print $6}')
time=$(date | awk '{print $4}')
fi
if [ $HOSTNAME = auros ] ; then
#Thu 06 Apr 2023 03:08:48 PM EDT
dd=$(date | awk '{print $2}')
mm=$(date | awk '{print $3}')
yy=$(date | awk '{print $4}')
time=$(date | awk '{print $5" "$6}')
fi

outf=$path/"$project"_diary.md #.txt
lastday=$($path/NEXTT | tail -3 | head -1 | awk '{print $1}')
if [ "$dd" != "$lastday" ]
then
echo "--- --- ---" >> $outf
echo "" >> $outf
fi  
echo "$dd $mm $yy, $time $HOSTNAME <br>" >> $outf
echo $@ >> $outf
echo "" >> $outf
$path/NEXTT
